version: '3'
services:
  atlassian-bitbucket:
    container_name: Bitbucket
    env_file: .env
    environment:
      - JDBC_PASSWORD=${PASSWORD}
      - JDBC_URL=jdbc:mysql://mysql:3306/bitbucketdb?useUnicode=true&characterEncoding=UTF8&sessionVariables=default_storage_engine=InnoDB&autoReconnect=true&useSSL=false
      - JDBC_USER=atlassian
      - SERVER_PROXY_NAME=bitbucket.${DOMAIN_ROOT:-.localhost}
      - SERVER_PROXY_PORT=443
      - SERVER_SCHEME=https
      - SERVER_SECURE=true
    depends_on:
      - mysql
    healthcheck:
      test: 'curl localhost:7990/status | grep -q RUNNING'
      interval: 1m
      start_period: 10m
      timeout: 10s
    image: 'atlassian/bitbucket:latest'
    network_mode: bridge
    ports:
      - '7990:7990'
      - '7999:7999'
    restart: unless-stopped
    volumes:
      - ./bitbucket:/var/atlassian/application-data/bitbucket:rw
      - ./configuration/mysql-connector-java-5.1.48-bin.jar:/var/atlassian/application-data/bitbucket/lib/mysql-connector-java-5.1.48-bin.jar:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.bitbucket.rule=Host(`bitbucket.${DOMAIN_ROOT:-.localhost}`)
      - traefik.http.routers.bitbucket.service=bitbucket
      #- traefik.http.routers.bitbucket.entrypoints=${SCHEME:-websecure}
      #- traefik.http.routers.bitbucket.tls.certresolver=letsencrypt
      #- traefik.http.routers.bitbucket.tls=true
      #- traefik.http.services.bitbucket.loadbalancer.server.port=8080

  atlassian-confluence:
    container_name: Confluence
    env_file: .env
    environment:
      #- ATL_DB_DRIVER=com.mysql.jdbc.Driver
      - JDBC_URL=jdbc:mysql://mysql:3306/confluencedb?useUnicode=true&characterEncoding=UTF8&sessionVariables=default_storage_engine=InnoDB&autoReconnect=true&useSSL=false
      - ATL_DB_TYPE=mysql
      - ATL_JDBC_PASSWORD=${PASSWORD}
      - ATL_JDBC_URL=jdbc:mysql://mysql:3306/confluencedb?useUnicode=true&autoReconnect=true&useSSL=false
      - ATL_JDBC_USER=atlassian
      - ATL_PROXY_NAME=confluence.${DOMAIN_ROOT:-.localhost}
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_PORT=8090
      - ATL_TOMCAT_SCHEME=http
      - ATL_TOMCAT_SECURE=false
    depends_on:
      - mysql
    healthcheck:
      test: 'curl localhost:8090/status | grep -q RUNNING'
      interval: 1m
      start_period: 10m
      timeout: 10s
    image: 'atlassian/confluence:latest'
    network_mode: bridge
    ports:
      - '8090:8090'
      - '8091:8091'
    restart: unless-stopped
    volumes:
      - ./confluence:/var/atlassian/application-data/confluence:rw
      - ./configuration/mysql-connector-java-8.0.21.jar:/opt/atlassian/confluence/WEB-INF/lib/mysql-connector-java-8.0.21.jar:rw
      - ./confluence/logs:/opt/atlassian/confluence/logs:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.confluence.rule=Host(`confluence.${DOMAIN_ROOT:-.localhost}`)
      - traefik.http.routers.confluence.service=confluence

  atlassian-jira:
    container_name: Jira
    env_file: .env
    environment:
      - ATL_DB_DRIVER=com.mysql.jdbc.Driver
      - ATL_DB_TYPE=mysql
      - ATL_JDBC_PASSWORD=${PASSWORD}
      - ATL_JDBC_URL=jdbc:mysql://mysql:3306/jiradb?useUnicode=true&autoReconnect=true&useSSL=false
      - ATL_JDBC_USER=atlassian
      - ATL_PROXY_NAME=jira.${DOMAIN_ROOT:-.localhost}
      - ATL_PROXY_PORT=88
      #- ATL_PROXY_PORT=443
      - ATL_TOMCAT_PORT=8080
      - ATL_TOMCAT_SCHEME=http
      - ATL_TOMCAT_SECURE=false
    depends_on:
      - mysql
    healthcheck:
      test: 'curl localhost:8080/status | grep -q RUNNING'
      interval: 1m
      start_period: 10m
      timeout: 10s
    image: 'atlassian/jira-software:latest'
    network_mode: bridge
    ports:
      - '88:8080'
    restart: unless-stopped
    volumes:
      - ./jira:/var/atlassian/application-data/jira:rw
      - ./configuration/mysql-connector-java-8.0.21.jar:/opt/atlassian/jira/lib/mysql-connector-java-8.0.21.jar:rw
      - ./jira/log:/opt/atlassian/jira/logs:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.jira.rule=Host(`jira.${DOMAIN_ROOT:-.localhost}`)
      - traefik.http.routers.jira.service=jira
      - traefik.http.routers.bitbucket.entrypoints=web
      - traefik.http.services.bitbucket.loadbalancer.server.port=88

  mysql:
    container_name: MySQL
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    healthcheck:
      test: '/usr/bin/mysql --user=healthcheck --password=healthcheck --execute "SHOW DATABASES;"'
      interval: 1m
      start_period: 1m
      timeout: 10s
    image: 'mysql:latest'
    network_mode: bridge
    ports:
      - '3306:3306'
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql:rw
      - ./configuration/conf.d/mysql.cnf:/etc/mysql/conf.d/my.cnf:rw

networks:
  default:
    external:
      name: bridge
  traefik:
    external: true
    name: traf-external
