version: '3'
services:
  atlassian-bitbucket:
    container_name: Bitbucket
    env_file: .env
    environment:
      - JDBC_PASSWORD=${PASSWORD}
      - JDBC_URL=jdbc:mysql://mysql:3306/bitbucketdb?useUnicode=true&characterEncoding=UTF8&sessionVariables=default_storage_engine=InnoDB&autoReconnect=true&useSSL=false
      - JDBC_USER=atlassian
      - SERVER_PROXY_NAME=bitbucket.${DOMAIN_ROOT:-.localhost}
      - SERVER_PROXY_PORT=443
      - SERVER_SCHEME=http
      - SERVER_SECURE=false
    depends_on:
      - mysql
    healthcheck:
      test: 'curl localhost:7990/status | grep -q RUNNING'
      interval: 1m
      start_period: 10m
      timeout: 10s
    image: 'atlassian/bitbucket:latest'
    networks:
      - traefik
      - default
    #network_mode: bridge
    # ports:
    #   - '7990:7990'
    #   - '7999:7999'
    restart: unless-stopped
    volumes:
      - ./bitbucket:/var/atlassian/application-data/bitbucket:rw
      - ./configuration/mysql-connector-java-5.1.48-bin.jar:/var/atlassian/application-data/bitbucket/lib/mysql-connector-java-5.1.48-bin.jar:rw
    labels:
      - "traefik.enable=true"
      # Web
      - "traefik.http.routers.bitbucket.rule=Host(`bitbucket.${DOMAIN_ROOT:-.localhost}`)"
      - "traefik.http.routers.bitbucket.tls=true"
      - "traefik.http.routers.bitbucket.tls.certresolver=letsencrypt"
      - "traefik.http.routers.bitbucket.entrypoints=web,websecure"
      - "traefik.http.routers.bitbucket.service=bitbucket-web"
      - "traefik.http.services.bitbucket-web.loadbalancer.server.port=7990"
      # SSH
      - "traefik.tcp.routers.bitbucket-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.bitbucket-ssh.entrypoints=bitbucket-ssh"
      - "traefik.tcp.routers.bitbucket-ssh.service=bitbucket-ssh"
      - "traefik.tcp.services.bitbucket-ssh.loadbalancer.server.port=7999"

  atlassian-confluence:
    container_name: Confluence
    env_file: .env
    environment:
      # - ATL_DB_DRIVER=com.mysql.jdbc.Driver
      # - JDBC_URL=jdbc:mysql://mysql:3306/confluencedb?useUnicode=true&characterEncoding=UTF8&sessionVariables=default_storage_engine=InnoDB&autoReconnect=true&useSSL=false
      - ATL_DB_TYPE=mysql
      - ATL_DB_DRIVER=com.mysql.cj.jdbc.Driver
      - ATL_DB_SCHEMA_NAME=jiradb
      - ATL_JDBC_URL=jdbc:mysql://localhost:3306/confluencedb
      - ATL_JDBC_USER=atlassian
      - ATL_JDBC_PASSWORD=${PASSWORD}
      # - ATL_PROXY_NAME=confluence.${DOMAIN_ROOT:-.localhost}
      # - ATL_PROXY_PORT=443
      # - ATL_TOMCAT_PORT=8090
      # - ATL_TOMCAT_SCHEME=http
      # - ATL_TOMCAT_SECURE=false
    depends_on:
      - mysql
    healthcheck:
      test: 'curl localhost:8090/status | grep -q RUNNING'
      interval: 1m
      start_period: 10m
      timeout: 10s
    image: 'atlassian/confluence:latest'
    networks:
      - traefik
      - default
    # network_mode: bridge
    ports:
      - '8090:8090'
      - '8091:8091'
    restart: unless-stopped
    volumes:
      - ./confluence:/var/atlassian/application-data/confluence:rw
      - ./configuration/mysql-connector-java-8.0.21.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-8.0.21.jar
      - ./confluence/logs:/opt/atlassian/confluence/logs:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.confluence.rule=Host(`confluence.${DOMAIN_ROOT:-.localhost}`)
      - traefik.http.routers.confluence.service=confluence

  atlassian-jira:
    container_name: Jira
    env_file: .env
    environment:
      - ATL_DB_DRIVER=com.mysql.jdbc.Driver
      - ATL_DB_TYPE=mysql
      - ATL_JDBC_PASSWORD=${PASSWORD}
      - ATL_JDBC_URL=jdbc:mysql://mysql:3306/jiradb?useUnicode=true&autoReconnect=true&useSSL=false
      - ATL_JDBC_USER=atlassian
      - ATL_PROXY_NAME=jira.${DOMAIN_ROOT:-.localhost}
      # - ATL_PROXY_PORT=88
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_PORT=8080
      - ATL_TOMCAT_SCHEME=http
      - ATL_TOMCAT_SECURE=false
    depends_on:
      - mysql
    healthcheck:
      test: 'curl localhost:8080/status | grep -q RUNNING'
      interval: 1m
      start_period: 10m
      timeout: 10s
    image: 'atlassian/jira-software:latest'
    networks:
      - traefik
      - default
    ports:
      - '88:8080'
    restart: unless-stopped
    volumes:
      - ./jira:/var/atlassian/application-data/jira:rw
      - ./configuration/mysql-connector-java-8.0.21.jar:/opt/atlassian/jira/lib/mysql-connector-java-8.0.21.jar:rw
      - ./jira/log:/opt/atlassian/jira/logs:rw
    labels:
      - "traefik.enable=true"
      # Web
      - "traefik.http.routers.jira.rule=Host(`jira.${DOMAIN_ROOT:-.localhost}`)"
      - "traefik.http.routers.jira.tls=true"
      - "traefik.http.routers.jira.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jira.entrypoints=websecure"
      - "traefik.http.routers.jira.service=jira-web"
      - "traefik.http.services.jira-web.loadbalancer.server.port=443"

  mysql:
    container_name: MySQL
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_ROOT_USER=root
      #- MYSQL_DATABASE=jiradb
      - MYSQL_USER=atlassian
      - MYSQL_PASSWORD=${PASSWORD}
    healthcheck:
      test: '/usr/bin/mysql --user=healthcheck --password=healthcheck --execute "SHOW DATABASES;"'
      interval: 1m
      start_period: 1m
      timeout: 10s
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    restart: unless-stopped
    networks:
      - default
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin, --default-storage-engine=INNODB, --max_allowed_packet=256M, --innodb_log_file_size=2GB, --transaction-isolation=READ-COMMITTED, --binlog_format=row]
    volumes:
      - ./mysql:/var/lib/mysql:rw
      - ./configuration/conf.d/mysql.cnf:/etc/mysql/conf.d/my.cnf:rw
      - ./configuration/mysql:/docker-entrypoint-initdb.d


networks:
  default:
  traefik:
    external: true
    name: reverse-proxy-docker-traefik_routing
