version: "3.3"

services:
  postgres:
    image: postgres:9.5-alpine
    container_name: postgres-bitbucket
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bitbucket #${BITBUCKET_DB:-bitbucket}
      POSTGRES_USER: bitbucket #${BITBUCKET_DB_USER:-bitbucket}
      POSTGRES_PASSWORD: "" #${BITBUCKET_DB_PASSWORD:-""}
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    stop_grace_period: 30s
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitbucket"]
      interval: 5s
      timeout: 5s
      retries: 5
  bitbucket:
    image: atlassian/bitbucket-server:7.0.2
    container_name: bitbucket
    labels:
      - "traefik.enable=true"
      # Web
      - "traefik.http.routers.router1.rule=Host(`bitbucket.wide.arpa`)"
      - "traefik.http.routers.router1.tls=true"
      - "traefik.http.routers.router1.tls.certresolver=route53"
      - "traefik.http.routers.router1.entrypoints=web"
      - "traefik.http.routers.router1.service=bitbucket-web"
      - "traefik.http.services.bitbucket-web.loadbalancer.server.port=7990"
      # SSH
      - "traefik.tcp.routers.router2.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.router2.entrypoints=bitbucket-ssh"
      - "traefik.tcp.routers.router2.service=bitbucket-ssh"
      - "traefik.tcp.services.bitbucket-ssh.loadbalancer.server.port=7999"
    environment:
      SERVER_PROXY_NAME: bitbucket.wide.arpa
      SERVER_PROXY_PORT: 666
      SERVER_SCHEME: http
      SERVER_SECURE: false
      JVM_MINIMUM_MEMORY: ${JVM_MINIMUM_MEMORY:-512m}
      JVM_MAXIMUM_MEMORY: ${JVM_MAXIMUM_MEMORY:-1024m}
    volumes:
      - data:/var/atlassian/application-data/bitbucket
    restart: unless-stopped
    stop_grace_period: 1m30s
    depends_on:
     - postgres
volumes:
  letsencrypt: {}
  data: {}
  db: {}
